# Generated by Django 5.2.9 on 2026-02-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='priorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
